### ISSUE TITLE
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

### ISSUE THREAD

**Issue by ArchLeaders** [ArchLeaders/BotwInstaller#9]
> Anonymous
# Unhandled Exception

> The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

```
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at BotwScripts.Lib.Common.Web.GitHub.GitHub.GetLatestRelease(String api, Int32 index)
   at BotwInstaller.Lib.Tasks.Cemu(Update update, Notify print, Config conf)
   at BotwInstaller.Lib.Installer.RunInstallerAsync(Notify print, Update update, Config conf)
   at BotwInstaller.Wizard.ViewModels.ShellViewModel.Install() in D:\Visual Studio\Projects\- Botw Scripts\BotwInstaller (RE)\BotwInstaller\BotwInstaller.Wizard\ViewModels\ShellViewModel.cs:line 91
```

<br>
## Install Log

```
Loading System Log . . .
[SEARCH.PYTHON] Python found on PATH in 'C:\Users\admin\AppData\Local\Programs\Python\Python38'
[SEARCH.BOTW] Start Unsafe
[SEARCH.BOTW][UNSAFE] Searching 'Z:\'
[SEARCH.CEMU][CHECKMLC] Mlc found in 'Z:\Programs\Cemu\mlc01'
[VERIFY.UKING] Returning US data check as '00050000101C9400'
[VERIFY.UKING] Game found in 'Z:\jscdi\Documents\DATA\EMULATORS\Cemu\GAMES\The Legend of Zelda Breath of the Wild [ALZE]'
[VERIFY.UKING] Returning US data check as '0005000E101C9400'
[VERIFY.UKING][UKING][CEMU] Update found in 'Z:\jscdi\Documents\DATA\EMULATORS\Cemu\BIN\mlc01\usr\title\0005000E\101C9400'
[VERIFY.UKING] Returning US data check as '0005000C101C9400'
[VERIFY.UKING][UKING][CEMU] DLC found in 'Z:\jscdi\Documents\DATA\EMULATORS\Cemu\BIN\mlc01\usr\title\0005000C\101C9400'
[INSTALL.BOTW] Copying 22647 files . . .
[INSTALL.BOTW] Copying 15219 files . . .
[INSTALL.CEMU] Downloading Cemu . . .
[INSTALL.CEMU] Downloading GFX . . .
[INSTALL.BCML] Installing BCML
[INSTALL.BCML] Installing CEF
[INSTALL.BCML] Installing TK
[INSTALL.BCML] Installing Runtimes
[INSTALL.CPPRUNTIME] Downloading Visual C++ Runtime . . .
[INSTALL.BCML] Creating Settings
[INSTALL.BOTW] Copied 22647 files
[INSTALL.BOTW] Copied 15219 files
---
Failed - The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---

```

## Config Info

```yml
ControllerApi: XInput
IsNX: False
```

## Directory Info

```yml
Dynamic: Z:\Programs\Cemu
Base: Z:\jscdi\Documents\DATA\EMULATORS\Cemu\GAMES\The Legend of Zelda Breath of the Wild [ALZE]
Update: Z:\jscdi\Documents\DATA\EMULATORS\Cemu\BIN\mlc01\usr\title\0005000E\101C9400
DLC: Z:\jscdi\Documents\DATA\EMULATORS\Cemu\BIN\mlc01\usr\title\0005000C\101C9400
BCML: C:\Users\admin\AppData\Local\bcml
MLC01: Z:\Programs\Cemu\mlc01
Python: C:\Users\admin\AppData\Local\Programs\Python\Python38
```

## Install Info

```yml
Cemu: False
Base: False
Update: True
DLC: True
Python: False
```

**Comment by ArchLeaders** [comment]
Fixed in commit [d285e475c6340ab53955fd750d5a580968ea06a6](https://github.com/ArchLeaders/BotwInstaller/commit/8f2edd6ca175266eec5ad055f5f29563a04646a2).
Allow the user to manually set a new timeout value.
